-- ============================================================
-- 199_seed_role_page_grants_locked.sql
--
-- PLA-0049 Phase 2 — replace-all seed for the 5 editable system
-- roles' users_roles_pages grants. Generated by
-- dev/scripts/capture_role_grants.sh from the live mmff_vector
-- state after gadmin finished editing the page-permissions grid.
--
-- Idempotent: DELETEs all rows for the 5 role UUIDs, then
-- INSERTs the captured set. Re-running produces identical output.
--
-- grp_global is NOT touched (its universal access is the floor —
-- managed by mig 193 and the auto-grant trigger). grp_external is
-- a template; tenants clone it. Neither appears in this seed.
--
-- DO NOT edit this file by hand. Re-run the capture script if
-- the canonical defaults change.
-- ============================================================

BEGIN;

WITH role_ids AS (
    SELECT users_roles_id, users_roles_code
      FROM users_roles
     WHERE users_roles_is_system = TRUE
       AND users_roles_id_subscription IS NULL
       AND users_roles_code IN (
         'grp_portfolio','grp_product','grp_team_lead',
         'grp_team_member','grp_stakeholder'
       )
)
DELETE FROM users_roles_pages
 WHERE users_roles_pages_id_role IN (SELECT users_roles_id FROM role_ids);

-- grp_portfolio grants
INSERT INTO users_roles_pages (users_roles_pages_id_page, users_roles_pages_id_role)
SELECT p.id,
       (SELECT users_roles_id FROM users_roles
          WHERE users_roles_code = 'grp_portfolio'
            AND users_roles_id_subscription IS NULL)
  FROM pages p
 WHERE p.key_enum IN ('dev-components','scope','planning','backlog','portfolio','portfolio-items','work-items','sprints','releases','topology','risk','user-management','admin-roles','library-releases','ws-workspaces','ws-artefact-types','ws-transition-rules','ws-flow-states','ws-flow-states-v2','theme','um-permissions','va-tenant-details','va-topology','va-topology-map','va-api-manager','dev-setup','dev-plans','dev-retros','dev-scope','dev-research','dev-reports','dev-shortcuts','dev-operations','dev-page-help','dev-ui-catalog','dev-icons','dev-api-v2-tests','dev-api-changelog','ws-custom-fields','ws-portfolio-model','ws-organisation','portfolio-settings','account-settings','preferences-navigation','notifications-manager')
   AND p.created_by      IS NULL
   AND p.subscription_id IS NULL
ON CONFLICT (users_roles_pages_id_page, users_roles_pages_id_role) DO NOTHING;

-- grp_product: no grants

-- grp_team_lead: no grants

-- grp_team_member grants
INSERT INTO users_roles_pages (users_roles_pages_id_page, users_roles_pages_id_role)
SELECT p.id,
       (SELECT users_roles_id FROM users_roles
          WHERE users_roles_code = 'grp_team_member'
            AND users_roles_id_subscription IS NULL)
  FROM pages p
 WHERE p.key_enum IN ('dashboard','my-vista','favourites','scope','planning','backlog','portfolio','portfolio-items','work-items','sprints','releases','topology','risk','theme','account-settings','preferences-navigation','notifications-manager')
   AND p.created_by      IS NULL
   AND p.subscription_id IS NULL
ON CONFLICT (users_roles_pages_id_page, users_roles_pages_id_role) DO NOTHING;

-- grp_stakeholder: no grants

-- ── Sanity ────────────────────────────────────────────────
DO $$
DECLARE n int;
BEGIN
    SELECT COUNT(*) INTO n
      FROM users_roles_pages rp
      JOIN users_roles r ON r.users_roles_id = rp.users_roles_pages_id_role
     WHERE r.users_roles_code IN ('grp_portfolio','grp_product','grp_team_lead','grp_team_member','grp_stakeholder');
    RAISE NOTICE 'PLA-0049 mig 199: % grants seeded across 5 editable system roles', n;
END $$;

COMMIT;
