#!/usr/bin/env python3
"""audit_codegraph_enrich.py — Phase B + C audit enrichment for V2A.

Reads the bare nodes.jsonl + edges.jsonl produced by the bash audit's
first pass, plus the two YAML registries (system_areas.yaml,
critical_path_seeds.yaml), and writes back enriched JSONL with the
following per-node fields appended:

  system            : name of the matched system area, or null
  tags              : list[str] — auth, authz, audit, security, error,
                      db, config, state, styled, dui (grep heuristics)
  generated         : bool — file declared "DO NOT EDIT" / "Code generated by"
  visibility        : "exported" | "internal"
  has_test          : bool
  test_path         : str | null
  in_critical_path  : bool
  critical_paths    : list[str] (seed names)
  in_cycle          : bool
  cycle_id          : int | null
  complexity        : float (composite 0-100)

This is the single place Phase B + C compute lives. The bash audit
calls this script after building nodes.jsonl + edges.jsonl; the script
overwrites nodes.jsonl in place with the enriched version.

Read-only against the repo (it greps source files but doesn't write
them). Idempotent.
"""

from __future__ import annotations

import json
import os
import re
import sys
from collections import defaultdict, deque
from pathlib import Path
from typing import Any

# ─── YAML loader (no PyYAML dep — keeps audit dep-free) ──────────────────────
# Vector ships zero Python deps for audit scripts. The two registries
# have a tightly constrained schema we can parse with a 40-line walker.


def parse_simple_yaml(text: str) -> dict:
    """Parse the constrained YAML used by audit registries.

    Supports: top-level lists keyed under one root key, each item a
    mapping with `name: str` and a single `prefixes:`/`files:` list of
    strings. Comments (`#`) and blank lines ignored. No anchors, no
    multi-line strings, no flow style.
    """
    result: dict[str, list[dict[str, Any]]] = {}
    root_key: str | None = None
    cur_item: dict[str, Any] | None = None
    cur_list_key: str | None = None
    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        # Root key: "<key>:"
        if not line.startswith(" ") and line.endswith(":"):
            root_key = line[:-1].strip()
            result[root_key] = []
            continue
        # Item start: "  - name: …"
        m = re.match(r"^  - name:\s*(.+)$", line)
        if m and root_key is not None:
            if cur_item is not None:
                result[root_key].append(cur_item)
            cur_item = {"name": m.group(1).strip()}
            cur_list_key = None
            continue
        # Item key with list: "    prefixes:" or "    files:"
        m = re.match(r"^    (\w+):\s*$", line)
        if m and cur_item is not None:
            cur_list_key = m.group(1)
            cur_item[cur_list_key] = []
            continue
        # List entry: "      - <value>"
        m = re.match(r"^      - (.+)$", line)
        if m and cur_item is not None and cur_list_key is not None:
            cur_item[cur_list_key].append(m.group(1).strip())
            continue
    if cur_item is not None and root_key is not None:
        result[root_key].append(cur_item)
    return result


# ─── Tag heuristics ─────────────────────────────────────────────────────────
# Each tag is (pattern, file-extensions-where-it-applies). Compiled once
# and applied via a single grep-equivalent per node.

TAG_PATTERNS: dict[str, re.Pattern[str]] = {
    "auth": re.compile(
        r"\b(login|session|cookie|password|jwt|dpop|refresh_token|"
        r"setCredentials|signIn|signOut)\b",
        re.I,
    ),
    "authz": re.compile(
        r"\b(useHasPermission|sentinel_can|roles_permissions|rbac|"
        r"hasPermission|requireRole|requirePermission|authz)\b",
    ),
    "audit": re.compile(
        r"\b(audit_log|audit_event|audit_trail|evidence|compliance_record|"
        r"history_table|change_history)\b",
    ),
    "security": re.compile(
        r"\b(csrf|dpop|csp|secret|credential|encrypt|decrypt|hmac|nonce|"
        r"sanitize|sanitise|xss)\b",
        re.I,
    ),
    "error": re.compile(
        r"\b(error_codes|httperr|usermessages|ProblemJSON|reportError|"
        r"ErrorBoundary|HTTPError)\b",
    ),
    "db": re.compile(
        # Match SQL keywords with FROM/INTO/TABLE to avoid catching the
        # word "SELECT" inside JSX/comments.
        r"\b(pgxpool|BEGIN\s|SELECT\s.+\s+FROM\s|INSERT\s+INTO\s|"
        r"UPDATE\s+\w+\s+SET\s|DELETE\s+FROM\s|CREATE\s+TABLE\s)\b",
    ),
    "config": re.compile(
        r"\b(os\.Getenv|process\.env\.|launch_config|feature_flag|"
        r"api_base_url|NEXT_PUBLIC_)\b",
    ),
    "state": re.compile(
        r"\b(useContext|createContext|useReducer|localStorage|indexedDB|"
        r"sessionStorage|createStore|useStore)\b",
    ),
    "styled": re.compile(r"globals\.css|@/app/globals\.css"),
    "dui": re.compile(r"\bdui-[a-zA-Z][\w-]*\b"),
}

GENERATED_PATTERNS = re.compile(
    r"(Code generated by|DO NOT EDIT|@generated|This file is auto-generated)",
    re.I,
)


def detect_tags(path: Path) -> tuple[list[str], bool]:
    """Return (matched-tag-list, generated-flag) for one source file.

    Reads the file once; runs all tag regexes over the buffer. Files
    that don't exist or can't decode as utf-8 get empty tags + False.
    """
    try:
        # Limit to first 200KB — guards against accidental huge files;
        # tags we care about always appear near the top.
        text = path.read_text(encoding="utf-8", errors="replace")[:200_000]
    except (OSError, UnicodeDecodeError):
        return [], False
    tags = [name for name, pat in TAG_PATTERNS.items() if pat.search(text)]
    generated = bool(GENERATED_PATTERNS.search(text[:2000]))
    # Filename-based generated heuristics (don't need to read content):
    if path.name.endswith((".gen.ts", ".gen.tsx", ".gen.go")):
        generated = True
    if path.name in ("siteAPI.yaml",):
        generated = True
    return tags, generated


def detect_test_path(node_id: str, all_ids: set[str]) -> str | None:
    """Locate a sibling test file for the given node id.

    Heuristics in order:
      - same dir, basename + .test.ts(x)
      - same dir, basename + _test.go
      - same dir, __tests__/<basename>.test.tsx
      - e2e/<route>.spec.mjs for app/(user)/<route>/page.tsx
    """
    p = Path(node_id)
    stem = p.stem
    parent = p.parent

    candidates = [
        parent / f"{stem}.test.tsx",
        parent / f"{stem}.test.ts",
        parent / "__tests__" / f"{stem}.test.tsx",
        parent / "__tests__" / f"{stem}.test.ts",
        parent / f"{stem}_test.go",
    ]
    for c in candidates:
        if str(c) in all_ids:
            return str(c)
        # The audit excludes test files from nodes (see find -not -name
        # *.test.ts), so also check existence on disk.
        if (Path(REPO_ROOT) / c).exists():
            return str(c)
    return None


def detect_visibility(path: Path) -> str:
    """Cheap TS/Go-aware visibility heuristic.

    TS: file exported from a sibling index.ts OR has a single named
    default export → "exported"; otherwise "internal".
    Go: package has any capitalised top-level identifier → "exported".
    """
    if not path.exists():
        return "internal"
    suffix = path.suffix
    try:
        text = path.read_text(encoding="utf-8", errors="replace")[:50_000]
    except OSError:
        return "internal"
    if suffix in (".ts", ".tsx"):
        # An index.ts re-exporting this file is the strongest signal,
        # but we'd need a second pass. As a cheap proxy: file declares
        # any `export ` keyword.
        return "exported" if re.search(r"^export\s", text, re.M) else "internal"
    if suffix == ".go":
        # Top-level capitalised identifier (func/var/type/const).
        return (
            "exported"
            if re.search(r"^(func|var|type|const)\s+[A-Z]", text, re.M)
            else "internal"
        )
    return "internal"


# ─── Critical-path BFS ───────────────────────────────────────────────────────


def compute_critical_paths(
    edges: list[dict], seeds: list[dict]
) -> dict[str, set[str]]:
    """Return node-id → set of seed names it's reachable FROM.

    Walks the undirected import graph: any file in the dependency
    closure of any seed (in either direction) counts as on its path.
    """
    adj: dict[str, list[str]] = defaultdict(list)
    for e in edges:
        adj[e["source"]].append(e["target"])
        adj[e["target"]].append(e["source"])

    result: dict[str, set[str]] = defaultdict(set)
    for seed in seeds:
        name = seed["name"]
        start_nodes = [f for f in seed["files"]]
        seen: set[str] = set()
        q: deque[str] = deque(start_nodes)
        while q:
            node = q.popleft()
            if node in seen:
                continue
            seen.add(node)
            for nbr in adj.get(node, ()):
                if nbr not in seen:
                    q.append(nbr)
        for nid in seen:
            result[nid].add(name)
    return result


# ─── Tarjan SCC (iterative — avoids Python recursion limit on big graphs) ───


def tarjan_scc(nodes: list[str], edges: list[dict]) -> dict[str, int]:
    """Return node-id → cycle_id (-1 if not in any non-trivial SCC).

    "Non-trivial" = component size > 1 OR a self-loop. Single nodes
    with no self-edges get cycle_id = -1.
    """
    succ: dict[str, list[str]] = defaultdict(list)
    for e in edges:
        succ[e["source"]].append(e["target"])

    index_counter = [0]
    stack: list[str] = []
    on_stack: set[str] = set()
    indices: dict[str, int] = {}
    lowlinks: dict[str, int] = {}
    components: list[list[str]] = []
    self_loops: set[str] = {e["source"] for e in edges if e["source"] == e["target"]}

    def strongconnect_iter(root: str) -> None:
        work: list[tuple[str, int]] = [(root, 0)]
        call_stack: list[str] = []
        while work:
            node, pi = work[-1]
            if pi == 0:
                indices[node] = index_counter[0]
                lowlinks[node] = index_counter[0]
                index_counter[0] += 1
                stack.append(node)
                on_stack.add(node)
                call_stack.append(node)
            neighbours = succ.get(node, ())
            if pi < len(neighbours):
                w = neighbours[pi]
                work[-1] = (node, pi + 1)
                if w not in indices:
                    work.append((w, 0))
                elif w in on_stack:
                    lowlinks[node] = min(lowlinks[node], indices[w])
            else:
                if lowlinks[node] == indices[node]:
                    component: list[str] = []
                    while True:
                        w = stack.pop()
                        on_stack.discard(w)
                        component.append(w)
                        if w == node:
                            break
                    components.append(component)
                work.pop()
                if work:
                    parent = work[-1][0]
                    lowlinks[parent] = min(lowlinks[parent], lowlinks[node])

    for n in nodes:
        if n not in indices:
            strongconnect_iter(n)

    out: dict[str, int] = {}
    next_id = 0
    for comp in components:
        if len(comp) > 1 or comp[0] in self_loops:
            for n in comp:
                out[n] = next_id
            next_id += 1
        else:
            out[comp[0]] = -1
    return out


# ─── Complexity composite ───────────────────────────────────────────────────


def compute_complexity(node: dict, max_sloc: float, max_fan: float) -> float:
    """Composite 0-100 score: sloc + fan + sensitive-tags + bridge + no-test penalty."""
    sloc_n = node.get("sloc", 0) / max(max_sloc, 1.0)
    fan_n = (node.get("fan_in", 0) + node.get("fan_out", 0)) / max(max_fan, 1.0)
    sens = len(
        [t for t in node.get("tags", []) if t in ("auth", "authz", "security", "audit")]
    )
    sens_n = min(sens / 4.0, 1.0)
    bridge_n = 1.0 if "bridge" in node.get("tags", []) else 0.0
    no_test = 0.0 if node.get("has_test") else 0.3
    raw = 0.35 * sloc_n + 0.30 * fan_n + 0.20 * sens_n + 0.05 * bridge_n + 0.10 * no_test
    return round(raw * 100, 2)


# ─── Main ───────────────────────────────────────────────────────────────────


def main() -> int:
    if len(sys.argv) != 5:
        print(
            f"usage: {sys.argv[0]} <repo_root> <nodes.jsonl> <edges.jsonl> "
            f"<out.jsonl>",
            file=sys.stderr,
        )
        return 2
    global REPO_ROOT
    REPO_ROOT, nodes_path, edges_path, out_path = sys.argv[1:5]

    # Load bare nodes + edges.
    nodes: list[dict] = []
    with open(nodes_path) as f:
        for line in f:
            line = line.strip()
            if line:
                nodes.append(json.loads(line))
    edges: list[dict] = []
    with open(edges_path) as f:
        for line in f:
            line = line.strip()
            if line:
                edges.append(json.loads(line))

    print(f"▶ enrich: {len(nodes)} nodes, {len(edges)} edges", file=sys.stderr)

    # Fan-in / fan-out (we recompute here so complexity has access without
    # having to wait for the jq stitch; jq's merge will just see equal values).
    fan_in: dict[str, int] = defaultdict(int)
    fan_out: dict[str, int] = defaultdict(int)
    for e in edges:
        fan_in[e["target"]] += 1
        fan_out[e["source"]] += 1
    import math
    for n in nodes:
        fi = fan_in.get(n["id"], 0)
        fo = fan_out.get(n["id"], 0)
        n["fan_in"] = fi
        n["fan_out"] = fo
        # criticality = fan_in * log(sloc+1), rounded to 2dp — matches jq.
        n["criticality"] = round(fi * math.log(n.get("sloc", 0) + 1), 2)

    # Load registries.
    systems_path = Path(REPO_ROOT) / "dev" / "audits" / "system_areas.yaml"
    seeds_path = Path(REPO_ROOT) / "dev" / "audits" / "critical_path_seeds.yaml"
    systems = parse_simple_yaml(systems_path.read_text()).get("systems", [])
    seeds = parse_simple_yaml(seeds_path.read_text()).get("seeds", [])
    print(
        f"  loaded {len(systems)} system areas, {len(seeds)} critical-path seeds",
        file=sys.stderr,
    )

    # System tagging (first-prefix-wins).
    def system_for(node_id: str) -> str | None:
        for sys_entry in systems:
            for prefix in sys_entry.get("prefixes", []):
                if node_id.startswith(prefix):
                    return sys_entry["name"]
        return None

    # Per-node grep + visibility + test detection.
    all_ids = {n["id"] for n in nodes}
    repo = Path(REPO_ROOT)
    print("▶ tagging nodes (grep + visibility + tests)…", file=sys.stderr)
    for n in nodes:
        path = repo / n["id"]
        tags, generated = detect_tags(path)
        n["tags"] = tags
        n["generated"] = generated
        n["visibility"] = detect_visibility(path)
        n["system"] = system_for(n["id"])
        test_path = detect_test_path(n["id"], all_ids)
        n["has_test"] = test_path is not None
        n["test_path"] = test_path

    # Critical-path BFS.
    print("▶ computing critical-path reachability…", file=sys.stderr)
    cpaths = compute_critical_paths(edges, seeds)
    for n in nodes:
        paths = sorted(cpaths.get(n["id"], set()))
        n["critical_paths"] = paths
        n["in_critical_path"] = len(paths) > 0

    # Cycle detection.
    print("▶ Tarjan SCC for cycle detection…", file=sys.stderr)
    cycle_ids = tarjan_scc([n["id"] for n in nodes], edges)
    for n in nodes:
        cid = cycle_ids.get(n["id"], -1)
        n["cycle_id"] = cid if cid >= 0 else None
        n["in_cycle"] = cid >= 0

    # Complexity composite.
    max_sloc = max((n.get("sloc", 0) for n in nodes), default=1)
    max_fan = max(
        (n.get("fan_in", 0) + n.get("fan_out", 0) for n in nodes), default=1
    )
    for n in nodes:
        n["complexity"] = compute_complexity(n, max_sloc, max_fan)

    # Write enriched JSONL.
    with open(out_path, "w") as f:
        for n in nodes:
            f.write(json.dumps(n, separators=(",", ":")) + "\n")

    # Summary stats for the stderr log.
    sys_count = sum(1 for n in nodes if n["system"])
    tag_count = sum(len(n["tags"]) for n in nodes)
    test_count = sum(1 for n in nodes if n["has_test"])
    cycle_count = sum(1 for n in nodes if n["in_cycle"])
    path_count = sum(1 for n in nodes if n["in_critical_path"])
    gen_count = sum(1 for n in nodes if n["generated"])
    print(
        f"  ✓ {sys_count} nodes tagged with a system area",
        f"  ✓ {tag_count} total tags applied",
        f"  ✓ {test_count} nodes have a detected test",
        f"  ✓ {cycle_count} nodes participate in a cycle",
        f"  ✓ {path_count} nodes reachable from a critical-path seed",
        f"  ✓ {gen_count} nodes flagged generated",
        sep="\n",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
