#!/usr/bin/env bash
# capture_role_grants.sh — PLA-0049 Phase 2.
#
# Captures the live mmff_vector users_roles_pages state for the 5
# editable system roles into a replace-all seed migration:
#
#   db/mmff_vector/schema/199_seed_role_page_grants_locked.sql
#
# Idempotent: re-running the migration always produces the same row
# set scoped to the 5 system role UUIDs (grp_portfolio, grp_product,
# grp_team_lead, grp_team_member, grp_stakeholder). grp_global keeps
# its universal grants (managed by mig 193); grp_external is a
# template (no grants).
#
# Usage: ./dev/scripts/capture_role_grants.sh
#
# After gadmin has finished editing the page-permissions grid, run
# this script. The migration it writes becomes the canonical seed for
# future fresh databases.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUT="$ROOT_DIR/db/mmff_vector/schema/199_seed_role_page_grants_locked.sql"

if [[ ! -f "$ROOT_DIR/backend/.env.dev" ]]; then
    echo "FATAL: backend/.env.dev not found" >&2
    exit 1
fi

PW=$(grep '^DB_PASSWORD=' "$ROOT_DIR/backend/.env.dev" | cut -d= -f2-)
PSQL="/opt/homebrew/opt/libpq/bin/psql"
CONN="host=localhost port=5435 user=mmff_dev dbname=mmff_vector"

ROLES=("grp_portfolio" "grp_product" "grp_team_lead" "grp_team_member" "grp_stakeholder")

# Probe DB liveness.
if ! PGPASSWORD="$PW" "$PSQL" "$CONN" -tAc "SELECT 1" > /dev/null 2>&1; then
    echo "FATAL: cannot reach mmff_vector at localhost:5435 — is the SSH tunnel up?" >&2
    exit 1
fi

cat > "$OUT" <<'EOF'
-- ============================================================
-- 199_seed_role_page_grants_locked.sql
--
-- PLA-0049 Phase 2 — replace-all seed for the 5 editable system
-- roles' users_roles_pages grants. Generated by
-- dev/scripts/capture_role_grants.sh from the live mmff_vector
-- state after gadmin finished editing the page-permissions grid.
--
-- Idempotent: DELETEs all rows for the 5 role UUIDs, then
-- INSERTs the captured set. Re-running produces identical output.
--
-- grp_global is NOT touched (its universal access is the floor —
-- managed by mig 193 and the auto-grant trigger). grp_external is
-- a template; tenants clone it. Neither appears in this seed.
--
-- DO NOT edit this file by hand. Re-run the capture script if
-- the canonical defaults change.
-- ============================================================

BEGIN;

WITH role_ids AS (
    SELECT users_roles_id, users_roles_code
      FROM users_roles
     WHERE users_roles_is_system = TRUE
       AND users_roles_id_subscription IS NULL
       AND users_roles_code IN (
         'grp_portfolio','grp_product','grp_team_lead',
         'grp_team_member','grp_stakeholder'
       )
)
DELETE FROM users_roles_pages
 WHERE users_roles_pages_id_role IN (SELECT users_roles_id FROM role_ids);

EOF

# Per role: dump as a single INSERT...SELECT keyed by role code +
# page key_enum so the SQL stays readable + portable across fresh DBs
# (UUIDs differ per seed but codes and key_enums are stable).
for code in "${ROLES[@]}"; do
    pages=$(PGPASSWORD="$PW" "$PSQL" "$CONN" -tAc "
        SELECT string_agg(quote_literal(p.key_enum), ',')
          FROM users_roles_pages rp
          JOIN pages p ON p.id = rp.users_roles_pages_id_page
          JOIN users_roles r ON r.users_roles_id = rp.users_roles_pages_id_role
         WHERE r.users_roles_code = '$code'
           AND p.created_by IS NULL
           AND p.subscription_id IS NULL
    " 2>/dev/null || true)
    if [[ -z "$pages" || "$pages" == "" ]]; then
        echo "-- $code: no grants" >> "$OUT"
        echo "" >> "$OUT"
        continue
    fi
    cat >> "$OUT" <<EOF
-- $code grants
INSERT INTO users_roles_pages (users_roles_pages_id_page, users_roles_pages_id_role)
SELECT p.id,
       (SELECT users_roles_id FROM users_roles
          WHERE users_roles_code = '$code'
            AND users_roles_id_subscription IS NULL)
  FROM pages p
 WHERE p.key_enum IN ($pages)
   AND p.created_by      IS NULL
   AND p.subscription_id IS NULL
ON CONFLICT (users_roles_pages_id_page, users_roles_pages_id_role) DO NOTHING;

EOF
done

cat >> "$OUT" <<'EOF'
-- ── Sanity ────────────────────────────────────────────────
DO $$
DECLARE n int;
BEGIN
    SELECT COUNT(*) INTO n
      FROM users_roles_pages rp
      JOIN users_roles r ON r.users_roles_id = rp.users_roles_pages_id_role
     WHERE r.users_roles_code IN ('grp_portfolio','grp_product','grp_team_lead','grp_team_member','grp_stakeholder');
    RAISE NOTICE 'PLA-0049 mig 199: % grants seeded across 5 editable system roles', n;
END $$;

COMMIT;
EOF

echo "wrote $OUT"
echo ""
echo "Summary:"
for code in "${ROLES[@]}"; do
    n=$(PGPASSWORD="$PW" "$PSQL" "$CONN" -tAc "
        SELECT COUNT(*)
          FROM users_roles_pages rp
          JOIN users_roles r ON r.users_roles_id = rp.users_roles_pages_id_role
         WHERE r.users_roles_code = '$code'
    ")
    printf "  %-20s %s pages\n" "$code" "$n"
done
